services:
  postgres:
    image: postgres:latest
    container_name: turingtest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iammm
      POSTGRES_DB: turing_test
    ports:
      - "15432:5432"
    volumes:
      - turingtest_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: turingtest-redis
    ports:
      - "16379:6379"
    volumes:
      - turingtest_redis_data:/data

volumes:
  turingtest_pg_data:
  turingtest_redis_data:
