services:
  turingtest-api:
    image: crpi-17xfv94wezytpemm.cn-beijing.personal.cr.aliyuncs.com/growforever/turingtest-api:latest
    container_name: turingtest-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      # 直接在这里声明所有必需的环境变量
      - DATABASE_URL=postgresql+asyncpg://postgres:iammm@turingtest-postgres:5432/turing_test
      - REDIS_URL=redis://turingtest-redis:6379/0
      - DEEPSEEK_API_KEY=sk-5399ca53700149b49e7830e6bdb4f5cf
    depends_on:
      - turingtest-postgres
      - turingtest-redis

  turingtest-postgres:
    image: crpi-17xfv94wezytpemm.cn-beijing.personal.cr.aliyuncs.com/geekreward/postgresql:latest
    container_name: turingtest-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iammm
      - POSTGRES_DB=turing_test
    ports:
      - "15432:5432"
    volumes:
      - turingtest_pg_data:/var/lib/postgresql/data

  turingtest-redis:
    image: crpi-17xfv94wezytpemm.cn-beijing.personal.cr.aliyuncs.com/growforever/redis:latest
    container_name: turingtest-redis
    restart: always
    ports:
      - "16379:6379"
    volumes:
      - turingtest_redis_data:/data

volumes:
  turingtest_pg_data:
  turingtest_redis_data:
